language: python

matrix:
  include:
    - os: linux
      sudo: false
      dist: bionic
      python: 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
    - os: linux
      sudo: false
      dist: bionic
      python: 3.7
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-8
            - ubuntu-toolchain-r-test
          packages:
            - clang-8
            - libclang-8-dev
            - llvm-8-tools
      env:
        - CC=clang-8
        - CXX=clang++-8

addons:
  apt:
    packages:
      - python-pip
      - libc6-dev
      - cmake
      - scons
      - gfortran
      - qt4-qmake
      - nvidia-cuda-toolkit

before_install:
  - uname
  - env | sort
  - cmake --version

install:
  - pip --version
  - pip install --upgrade pip
  - pip install lit pex pycodestyle

before_script:
  - git submodule add https://github.com/google/googletest.git gtest
  - git apply ./gtest.patch

script:
  - mkdir -p "$HOME/install" "$HOME/build"
  - cd "$HOME/build"
  - cmake "$TRAVIS_BUILD_DIR" -DCPACK_GENERATOR="TGZ;DEB"
  - VERBOSE=1 make all
  - CTEST_OUTPUT_ON_FAILURE=1 make test
  - VERBOSE=1 make package
  - VERBOSE=1 DESTDIR="$HOME/install" make install
